### ISSUE TITLE
CPAN upload

### ISSUE THREAD

**Issue by mtsanovv** [sciurius/wxPerl#1]
Hi Johan,

I came across your article https://dev.to/sciurius/wxperl-revival-5fde and I was very pleased to see that the wxPerl project has been revived!

I tried getting wxPerl to work with wxWidgets 3.2 and Perl (5.34?) back in 2022, but I couldn't make it - there were some macOS/Windows challenges that I could not overcome if my memory serves well.

Can we expect a CPAN release (even as a different package) of this project?

Thanks for the hard work and amazing contribution!

Best regards,
Marin

**Comment by sciurius** [comment]
Hi Marin,

I 'revived' wxPerl for one simple reason: I need it. That means that I will only make changes necessary for my own purposes.

Making it fully up-to-date with Wx 3.2 requires a lot of time and energy, which I don't have. Also, it requires an amount of XS, wxWidgets and g++ expertise that I don't have.

So for the time being I do not consider an official take-over. I won't be able to provide the necessary support.

**Comment by mtsanovv** [comment]
Thanks for your reply & your efforts. Please let the world know in case you decide to publish your wxPerl on CPAN someday :)
